logging:
  level:
    root: INFO
    org:
      springframework:
        boot:
          autoconfigure: ERROR

spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: false
