version: '3.7'
services:
  rdb:
    platform: linux/x86_64
    image: mysql:8
    restart: always
    container_name: starter-rdb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: starter
      MYSQL_USER: starter
      MYSQL_PASSWORD: starter
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/starter/data:/var/lib/mysql
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/Users/sungsupark/dev/personal/kotlin-spring-multi-module-starter/db/elasticsearch/starter/data
    ports:
      - 9200:9200
    networks:
      - internal-network
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/Users/sungsupark/dev/personal/kotlin-spring-multi-module-starter/db/elasticsearch/starter/data
    networks:
      - internal-network
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/Users/sungsupark/dev/personal/kotlin-spring-multi-module-starter/db/elasticsearch/starter/data
    networks:
      - internal-network
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - internal-network
    depends_on:
      - es01
  cerebro:
    image: lmenezes/cerebro:0.9.4
    container_name: cerebro
    environment:
      - CEREBRO_PORT=8080
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 8080:8080
    networks:
      - internal-network
    depends_on:
      - es01

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  internal-network:
    driver: bridge
