spring:
  config:
    activate:
      on-profile: clients

clients:
  internal:
    admin: http://localhost:9901
    file: http://localhost:9902

--- # local

logging:
  level:
    reactor.netty.http.client: INFO

