spring:
  application:
    name: starter-admin
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  messages:
    encoding: UTF-8
  profiles:
    include:
      - common
      - jasypt
      - rdb
      - security
      - clients
      - tempfile

server:
  port: 9901
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  tomcat:
    accesslog:
      enabled: true
      directory:
      prefix: admin.access-log
    basedir: logs/server/admin/
