logging:
  level:
    root: INFO

spring:
  config:
    activate:
      on-profile: release

event:
  security:
    cors-allowed-origin:
    swagger-ui-path: /document/swagger-ui/index.html
  url:
    mobile: m.webtoons.com
    webtoon-gw-photo-infra: https://webtoon-phinf.pstatic.net


springdoc:
  packagesToScan: com.starter.api.app
  api-docs:
    enabled: false
    path: /document/api-docs
  swagger-ui:
    enabled: false
    path: /document/swagger-ui.html

sleuth:
  sampler:
    probability: 1.0
