### 파일 업로드 (ZIP)
POST /api/v1/files/upload
Host: localhost:9902
Content-Type: multipart/form-data; boundary=Webappboundary

--Webappboundary
Content-Disposition: form-data; name="file"; filename="5g.zip"

< 5g.zip
--Webappboundary
Content-Disposition: form-data; name="fileName"

5g_test.zip
--Webappboundary
Content-Disposition: form-data; name="fileType"

BASIC
--Webappboundary
Content-Disposition: form-data; name="description"

test file
--Webappboundary
Content-Disposition: form-data; name="uploadDirectoryType"

REPOSITORY


### 파일 업로드 (PNG)
POST /api/v1/files/upload
Host: localhost:9902
Accept: application/json
Content-Type: multipart/form-data; boundary=Webappboundary

--Webappboundary
Content-Disposition: form-data; name="file"; filename="test.png"

< test.png
--Webappboundary
Content-Disposition: form-data; name="fileName"

ss_test.png
--Webappboundary
Content-Disposition: form-data; name="fileType"

BASIC
--Webappboundary
Content-Disposition: form-data; name="description"

test file
--Webappboundary
Content-Disposition: form-data; name="uploadDirectoryType"

REPOSITORY

