

### crate member
POST /api/users
Host: localhost:9901
Content-Type: application/json

{
  "name": "test"
}

### get member
GET /api/members/3cb62d2e-b613-4fd2-b252-73a8970efc73
Host: localhost:9901

### get members by name
GET /api/members/name?name=test
Host: localhost:9901
