spring:
  application:
    name: starter-admin
  messages:
    encoding: UTF-8
  profiles:
    include:
      - common
      - jasypt
      - rdb
      - security
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /static/**

server:
  port: 9901
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  tomcat:
    accesslog:
      enabled: true
      directory:
      prefix: admin.access-log
    basedir: logs/tomcat/admin/
