### crate users
POST /api/v1/users
Host: localhost:9901
Accept: application/json
Content-Type: application/json

{"email":"sungsu9022@naver.com","userName":"sungsu"}

### get user
GET /api/v1/users/879d25a2-be22-462d-a3b8-cec61c1b6976
Accept: application/json
Host: localhost:9901

### get users
GET /api/v1/users
Accept: application/json
Host: localhost:9901

### get users (userName)
GET /api/v1/users?userName=sungsu2
Accept: application/json
Host: localhost:9901

### patch user
PATCH /api/v1/users/879d25a2-be22-462d-a3b8-cec61c1b6976
Accept: application/json
Host: localhost:9901
Content-Type: application/json

{"userName": "changed"}


### delete user
DELETE /api/v1/users/d50bddf9-0b57-46a1-8ab0-d85e4dd0b5c7
Accept: application/json
Host: localhost:9901

