spring:
  application:
    name: starter-file
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  profiles:
    include:
      - rdb
      - jasypt
      - common
      - security
      - s3
      - tempfile

server:
  port: 9903
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  tomcat:
    accesslog:
      enabled: true
      directory:
      prefix: user.access-log
    basedir: logs/server/file/

springdoc:
  packagesToScan: com.starter.file.app
  api-docs:
    enabled: true
    path: /document/api-docs
  swagger-ui:
    enabled: true
    path: /document/swagger-ui.html
