### 2.1.1 문서 색인1

PUT /my_index/_doc/2
Host: localhost:9200
Content-Type: application/json

{
  "title": "Hello world2",
  "views": 1234,
  "public": true,
  "created" : "2023-11-18T18:05:00.000Z"
}

### 2.1.1 문서 색인2
POST /my_index/_doc
Host: localhost:9200
Content-Type: application/json

{
  "title": "Hello world3",
  "views": 1234,
  "public": true,
  "created" : "2023-11-18T18:06:00.000Z"
}

### 2.1.2  문서 조회
GET /my_index/_doc/1
Host: localhost:9200

### 2.1.3 문서 업데이트
POST /my_index/_update/1
Host: localhost:9200
Content-Type: application/json

{
    "doc": {
      "title": "Hello world updated"
    }
}

### 2.1.4 문서 검색
GET /my_index/_search
Host: localhost:9200
Content-Type: application/json

{
  "query": {
    "match": {
      "title": "hello world"
    }
  }
}

### 2.1.5 문서 삭제
DELETE /my_index/_doc/1
Host: localhost:9200
Content-Type: application/json
